export const ALL_VEHICLES_SUCCESS = 'ALL_VEHICLES_SUCCESS'
export const ALL_VEHICLES_FAIL = 'ALL_VEHICLES_FAIL'

export const VEHICLE_DETAILS_SUCCESS = 'VEHICLE_DETAILS_SUCCESS'
export const VEHICLE_DETAILS_FAIL = 'VEHICLE_DETAILS_SUCCESS'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'