export const ALL_VEHICLES_SUCCESS = 'ALL_VEHICLES_SUCCESS'
export const ALL_VEHICLES_FAIL = 'ALL_VEHICLES_FAIL'

export const VEHICLE_DETAILS_SUCCESS = 'VEHICLE_DETAILS_SUCCESS'
export const VEHICLE_DETAILS_FAIL = 'VEHICLE_DETAILS_SUCCESS'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const REVIEW_AVAILABILITY_REQUEST = 'REVIEW_AVAILABILITY_REQUEST'
export const REVIEW_AVAILABILITY_SUCCESS = 'REVIEW_AVAILABILITY_SUCCESS'
export const REVIEW_AVAILABILITY_FAIL = 'REVIEW_AVAILABILITY_FAIL'

export const ADMIN_VEHICLES_REQUEST = 'ADMIN_VEHICLES_REQUEST'
export const ADMIN_VEHICLES_SUCCESS = 'ADMIN_VEHICLES_SUCCESS'
export const ADMIN_VEHICLES_FAIL = 'ADMIN_VEHICLES_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'